version: '3.8'

services:
  app:
    build: .
    ports:
      - "3005:3005"
    environment:
      - DB_URL=jdbc:postgresql://db:5432/prueba
      - DB_USERNAME=postgres
      - DB_PASSWORD=lrch25tec
      - JWT_SECRET=Lu1s5pR1nGJ4v4m4sS3gur0Yf1j0DeS4rr0ll0
      - JWT_ACCESS_TOKEN_EXPIRATION=600000
      - JWT_REFRESH_TOKEN_EXPIRATION=900000
      - SERVER_PORT=3005
    depends_on:
      - db
    networks:
      - spring-db-network

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=prueba
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=lrch25tec
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - spring-db-network

volumes:
  postgres_data:

networks:
  spring-db-network:
    driver: bridge